In [1]:
import numpy as np
import pandas as pd

In [2]:
credit_df = pd.read_csv(r"C:\Users\ni\Desktop\credit_risk_predictor\raw_data\UCI_Credit_Card.csv")
credit_df

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,2,2,2,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,2,2,2,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,2,2,1,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,220000.0,1,3,1,39,0,0,0,0,...,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0,0
29996,29997,150000.0,1,3,2,43,-1,-1,-1,-1,...,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0,0
29997,29998,30000.0,1,2,2,37,4,3,2,-1,...,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0,1
29998,29999,80000.0,1,3,1,41,1,-1,0,0,...,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0,1
29999,30000,50000.0,1,2,1,46,0,0,0,0,...,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0,1

In [3]:
credit_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          30000 non-null  int64
 1   LIMIT_BAL                   30000 non-null  float64
 2   SEX                         30000 non-null  int64
 3   EDUCATION                   30000 non-null  int64
 4   MARRIAGE                    30000 non-null  int64
 5   AGE                         30000 non-null  int64
 6   PAY_0                       30000 non-null  int64
 7   PAY_2                       30000 non-null  int64
 8   PAY_3                       30000 non-null  int64
 9   PAY_4                       30000 non-null  int64
 10  PAY_5                       30000 non-null  int64
 11  PAY_6                       30000 non-null  int64
 12  BILL_AMT1                   30000 non-null  float64
 13  BILL_AMT2                   30000 non-null  float64
 14  BILL_AMT3                   30000 non-null  float64
 15  BILL_AMT4                   30000 non-null  float64
 16  BILL_AMT5                   30000 non-null  float64
 17  BILL_AMT6                   30000 non-null  float64
 18  PAY_AMT1                    30000 non-null  float64
 19  PAY_AMT2                    30000 non-null  float64
 20  PAY_AMT3                    30000 non-null  float64
 21  PAY_AMT4                    30000 non-null  float64
 22  PAY_AMT5                    30000 non-null  float64
 23  PAY_AMT6                    30000 non-null  float64
 24  default.payment.next.month  30000 non-null  int64
dtypes: float64(13), int64(12)
memory usage: 5.7 MB

In [4]:
credit_df.describe()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
count,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,...,30000.000000,30000.000000,30000.000000,30000.000000,3.000000e+04,30000.00000,30000.000000,30000.000000,30000.000000,30000.000000
mean,15000.500000,167484.322667,1.603733,1.853133,1.551867,35.485500,-0.016700,-0.133767,-0.166200,-0.220667,...,43262.948967,40311.400967,38871.760400,5663.580500,5.921163e+03,5225.68150,4826.076867,4799.387633,5215.502567,0.221200
std,8660.398374,129747.661567,0.489129,0.790349,0.521970,9.217904,1.123802,1.197186,1.196868,1.169139,...,64332.856134,60797.155770,59554.107537,16563.280354,2.304087e+04,17606.96147,15666.159744,15278.305679,17777.465775,0.415062
min,1.000000,10000.000000,1.000000,0.000000,0.000000,21.000000,-2.000000,-2.000000,-2.000000,-2.000000,...,-170000.000000,-81334.000000,-339603.000000,0.000000,0.000000e+00,0.00000,0.000000,0.000000,0.000000,0.000000
25%,7500.750000,50000.000000,1.000000,1.000000,1.000000,28.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,2326.750000,1763.000000,1256.000000,1000.000000,8.330000e+02,390.00000,296.000000,252.500000,117.750000,0.000000
50%,15000.500000,140000.000000,2.000000,2.000000,2.000000,34.000000,0.000000,0.000000,0.000000,0.000000,...,19052.000000,18104.500000,17071.000000,2100.000000,2.009000e+03,1800.00000,1500.000000,1500.000000,1500.000000,0.000000
75%,22500.250000,240000.000000,2.000000,2.000000,2.000000,41.000000,0.000000,0.000000,0.000000,0.000000,...,54506.000000,50190.500000,49198.250000,5006.000000,5.000000e+03,4505.00000,4013.250000,4031.500000,4000.000000,0.000000
max,30000.000000,1000000.000000,2.000000,6.000000,3.000000,79.000000,8.000000,8.000000,8.000000,8.000000,...,891586.000000,927171.000000,961664.000000,873552.000000,1.684259e+06,896040.00000,621000.000000,426529.000000,528666.000000,1.000000

In [5]:
"""
Select only relevant columns for credit risk modeling.
Keeps financial and repayment-related features required for
feature engineering and removes all unnecessary attributes.
"""

relevant_columns = [
    "LIMIT_BAL",
    "PAY_0", "PAY_2", "PAY_3", "PAY_4", "PAY_5", "PAY_6",
    "BILL_AMT1", "BILL_AMT2", "BILL_AMT3",
    "BILL_AMT4", "BILL_AMT5", "BILL_AMT6",
    "PAY_AMT1", "PAY_AMT2", "PAY_AMT3",
    "PAY_AMT4", "PAY_AMT5", "PAY_AMT6",
    "default.payment.next.month"
]

credit_df = credit_df[relevant_columns]

In [6]:
credit_df

,LIMIT_BAL,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,BILL_AMT2,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,20000.0,2,2,-1,-1,-2,-2,3913.0,3102.0,689.0,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,120000.0,-1,2,0,0,0,2,2682.0,1725.0,2682.0,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,90000.0,0,0,0,0,0,0,29239.0,14027.0,13559.0,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,50000.0,0,0,0,0,0,0,46990.0,48233.0,49291.0,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,50000.0,-1,0,-1,0,0,0,8617.0,5670.0,35835.0,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,220000.0,0,0,0,0,0,0,188948.0,192815.0,208365.0,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0,0
29996,150000.0,-1,-1,-1,-1,0,0,1683.0,1828.0,3502.0,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0,0
29997,30000.0,4,3,2,-1,0,0,3565.0,3356.0,2758.0,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0,1
29998,80000.0,1,-1,0,0,0,-1,-1645.0,78379.0,76304.0,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0,1
29999,50000.0,0,0,0,0,0,0,47929.0,48905.0,49764.0,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0,1

In [7]:
"""
Rename key columns for clarity and consistency
"""

credit_df = credit_df.rename(columns={
    "LIMIT_BAL": "credit_limit",
    "default.payment.next.month": "default"
})

In [8]:
# Feature Engineering

In [9]:
"""
Create core financial features from bill and payment data
"""

# Current outstanding balance (most recent bill)
credit_df["current_outstanding_balance"] = credit_df["BILL_AMT1"]

# Average bill amount
credit_df["avg_bill_amount"] = credit_df[
    ["BILL_AMT1", "BILL_AMT2", "BILL_AMT3", "BILL_AMT4", "BILL_AMT5", "BILL_AMT6"]
].mean(axis=1)

# Total paid amount
credit_df["total_paid"] = credit_df[
    ["PAY_AMT1", "PAY_AMT2", "PAY_AMT3", "PAY_AMT4", "PAY_AMT5", "PAY_AMT6"]
].sum(axis=1)

In [10]:
credit_df

,credit_limit,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,BILL_AMT2,BILL_AMT3,...,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default,current_outstanding_balance,avg_bill_amount,total_paid
0,20000.0,2,2,-1,-1,-2,-2,3913.0,3102.0,689.0,...,0.0,689.0,0.0,0.0,0.0,0.0,1,3913.0,1284.000000,689.0
1,120000.0,-1,2,0,0,0,2,2682.0,1725.0,2682.0,...,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1,2682.0,2846.166667,5000.0
2,90000.0,0,0,0,0,0,0,29239.0,14027.0,13559.0,...,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0,29239.0,16942.166667,11018.0
3,50000.0,0,0,0,0,0,0,46990.0,48233.0,49291.0,...,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0,46990.0,38555.666667,8388.0
4,50000.0,-1,0,-1,0,0,0,8617.0,5670.0,35835.0,...,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0,8617.0,18223.166667,59049.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,220000.0,0,0,0,0,0,0,188948.0,192815.0,208365.0,...,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0,0,188948.0,120891.500000,42550.0
29996,150000.0,-1,-1,-1,-1,0,0,1683.0,1828.0,3502.0,...,1837.0,3526.0,8998.0,129.0,0.0,0.0,0,1683.0,3530.333333,14490.0
29997,30000.0,4,3,2,-1,0,0,3565.0,3356.0,2758.0,...,0.0,0.0,22000.0,4200.0,2000.0,3100.0,1,3565.0,11749.333333,31300.0
29998,80000.0,1,-1,0,0,0,-1,-1645.0,78379.0,76304.0,...,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0,1,-1645.0,44435.166667,147181.0
29999,50000.0,0,0,0,0,0,0,47929.0,48905.0,49764.0,...,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0,1,47929.0,38479.000000,8308.0

In [11]:
"""
Create repayment strength indicator
"""

total_bill = credit_df[
    ["BILL_AMT1", "BILL_AMT2", "BILL_AMT3", "BILL_AMT4", "BILL_AMT5", "BILL_AMT6"]
].sum(axis=1)

credit_df["payment_ratio"] = credit_df["total_paid"] / (total_bill + 1)  # avoid division by zero

In [12]:
"""
Create delay-related behavioral features
"""

pay_cols = ["PAY_0", "PAY_2", "PAY_3", "PAY_4", "PAY_5", "PAY_6"]

# Number of late payments
credit_df["num_late_payments"] = (credit_df[pay_cols] > 0).sum(axis=1)

# Average delay
credit_df["avg_delay"] = credit_df[pay_cols].mean(axis=1)

# Maximum delay
credit_df["max_delay"] = credit_df[pay_cols].max(axis=1)

# Most recent delay
credit_df["recent_delay"] = credit_df["PAY_0"]

In [13]:
credit_df

,credit_limit,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,BILL_AMT2,BILL_AMT3,...,PAY_AMT6,default,current_outstanding_balance,avg_bill_amount,total_paid,payment_ratio,num_late_payments,avg_delay,max_delay,recent_delay
0,20000.0,2,2,-1,-1,-2,-2,3913.0,3102.0,689.0,...,0.0,1,3913.0,1284.000000,689.0,0.089422,2,-0.333333,2,2
1,120000.0,-1,2,0,0,0,2,2682.0,1725.0,2682.0,...,2000.0,1,2682.0,2846.166667,5000.0,0.292774,2,0.500000,2,-1
2,90000.0,0,0,0,0,0,0,29239.0,14027.0,13559.0,...,5000.0,0,29239.0,16942.166667,11018.0,0.108387,0,0.000000,0,0
3,50000.0,0,0,0,0,0,0,46990.0,48233.0,49291.0,...,1000.0,0,46990.0,38555.666667,8388.0,0.036259,0,0.000000,0,0
4,50000.0,-1,0,-1,0,0,0,8617.0,5670.0,35835.0,...,679.0,0,8617.0,18223.166667,59049.0,0.540049,0,-0.333333,0,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,220000.0,0,0,0,0,0,0,188948.0,192815.0,208365.0,...,1000.0,0,188948.0,120891.500000,42550.0,0.058661,0,0.000000,0,0
29996,150000.0,-1,-1,-1,-1,0,0,1683.0,1828.0,3502.0,...,0.0,0,1683.0,3530.333333,14490.0,0.684039,0,-0.666667,0,-1
29997,30000.0,4,3,2,-1,0,0,3565.0,3356.0,2758.0,...,3100.0,1,3565.0,11749.333333,31300.0,0.443991,3,1.333333,4,4
29998,80000.0,1,-1,0,0,0,-1,-1645.0,78379.0,76304.0,...,1804.0,1,-1645.0,44435.166667,147181.0,0.552042,1,-0.166667,1,1
29999,50000.0,0,0,0,0,0,0,47929.0,48905.0,49764.0,...,1000.0,1,47929.0,38479.000000,8308.0,0.035985,0,0.000000,0,0

In [14]:
"""
Create credit utilization feature
"""

credit_df["credit_utilization"] = (
    credit_df["current_outstanding_balance"] / (credit_df["credit_limit"] + 1)
)

In [15]:
credit_df

,credit_limit,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,BILL_AMT2,BILL_AMT3,...,default,current_outstanding_balance,avg_bill_amount,total_paid,payment_ratio,num_late_payments,avg_delay,max_delay,recent_delay,credit_utilization
0,20000.0,2,2,-1,-1,-2,-2,3913.0,3102.0,689.0,...,1,3913.0,1284.000000,689.0,0.089422,2,-0.333333,2,2,0.195640
1,120000.0,-1,2,0,0,0,2,2682.0,1725.0,2682.0,...,1,2682.0,2846.166667,5000.0,0.292774,2,0.500000,2,-1,0.022350
2,90000.0,0,0,0,0,0,0,29239.0,14027.0,13559.0,...,0,29239.0,16942.166667,11018.0,0.108387,0,0.000000,0,0,0.324874
3,50000.0,0,0,0,0,0,0,46990.0,48233.0,49291.0,...,0,46990.0,38555.666667,8388.0,0.036259,0,0.000000,0,0,0.939781
4,50000.0,-1,0,-1,0,0,0,8617.0,5670.0,35835.0,...,0,8617.0,18223.166667,59049.0,0.540049,0,-0.333333,0,-1,0.172337
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,220000.0,0,0,0,0,0,0,188948.0,192815.0,208365.0,...,0,188948.0,120891.500000,42550.0,0.058661,0,0.000000,0,0,0.858851
29996,150000.0,-1,-1,-1,-1,0,0,1683.0,1828.0,3502.0,...,0,1683.0,3530.333333,14490.0,0.684039,0,-0.666667,0,-1,0.011220
29997,30000.0,4,3,2,-1,0,0,3565.0,3356.0,2758.0,...,1,3565.0,11749.333333,31300.0,0.443991,3,1.333333,4,4,0.118829
29998,80000.0,1,-1,0,0,0,-1,-1645.0,78379.0,76304.0,...,1,-1645.0,44435.166667,147181.0,0.552042,1,-0.166667,1,1,-0.020562
29999,50000.0,0,0,0,0,0,0,47929.0,48905.0,49764.0,...,1,47929.0,38479.000000,8308.0,0.035985,0,0.000000,0,0,0.958561

In [16]:
"""
Remove raw columns after feature engineering
"""

raw_columns = [
    "PAY_0", "PAY_2", "PAY_3", "PAY_4", "PAY_5", "PAY_6",
    "BILL_AMT1", "BILL_AMT2", "BILL_AMT3",
    "BILL_AMT4", "BILL_AMT5", "BILL_AMT6",
    "PAY_AMT1", "PAY_AMT2", "PAY_AMT3",
    "PAY_AMT4", "PAY_AMT5", "PAY_AMT6"
]

credit_df = credit_df.drop(columns=raw_columns)

In [17]:
credit_df

,credit_limit,default,current_outstanding_balance,avg_bill_amount,total_paid,payment_ratio,num_late_payments,avg_delay,max_delay,recent_delay,credit_utilization
0,20000.0,1,3913.0,1284.000000,689.0,0.089422,2,-0.333333,2,2,0.195640
1,120000.0,1,2682.0,2846.166667,5000.0,0.292774,2,0.500000,2,-1,0.022350
2,90000.0,0,29239.0,16942.166667,11018.0,0.108387,0,0.000000,0,0,0.324874
3,50000.0,0,46990.0,38555.666667,8388.0,0.036259,0,0.000000,0,0,0.939781
4,50000.0,0,8617.0,18223.166667,59049.0,0.540049,0,-0.333333,0,-1,0.172337
...,...,...,...,...,...,...,...,...,...,...,...
29995,220000.0,0,188948.0,120891.500000,42550.0,0.058661,0,0.000000,0,0,0.858851
29996,150000.0,0,1683.0,3530.333333,14490.0,0.684039,0,-0.666667,0,-1,0.011220
29997,30000.0,1,3565.0,11749.333333,31300.0,0.443991,3,1.333333,4,4,0.118829
29998,80000.0,1,-1645.0,44435.166667,147181.0,0.552042,1,-0.166667,1,1,-0.020562
29999,50000.0,1,47929.0,38479.000000,8308.0,0.035985,0,0.000000,0,0,0.958561

In [18]:
"""
Save the cleaned and feature-engineered dataset
for use in EDA and modeling notebooks
"""

credit_df.to_csv(r"C:\Users\ni\Desktop\credit_risk_predictor\cleaned_data\credit_data.csv", index=False)